# NOTE: clear cache/planner/* if you want fresh planner outputs.
python src/run.py phase3 \
  --data_dir /data/GNN-RAG/datasets/webqsp \
  --split dev \
  --reader hf \
  --model_path /data/GNN-RAG/models/Llama-2-7b-chat-hf \
  --attn_impl flash_attention_2 \
  --chat_template on \
  --batch_size 8 \
  --device auto \
  --device_map auto \
  --dtype float16 \
  --save_evidence \
  --save_prompt \
  --entity_name_map src/entities_names.json \
  --entity_emb entity_emb_sbert_768d.npy \
  --relation_emb relation_emb_sbert_768d.npy \
  --question_emb question_emb_sbert_768d_dev.npy \
  --planner hf \
  --planner_sem_model /data/GNN-RAG/models/all-mpnet-base-v2 \
  --planner_sem_offline \
  --planner_max_new_tokens 128 \
  --save_planner_raw \
  --path_topk_proposal 10 \
  --path_topk 5 \
  --path_max_len 2 \
  --hybrid_alpha 0.55 \
  --hybrid_beta 0.20 \
  --hybrid_gamma 0.15 \
  --hybrid_delta 0.10 \
  --progress
