python src/run.py phase2 \
  --data_dir /data/GNN-RAG/datasets/webqsp \
  --split dev \
  --reader hf \
  --model_path /data/GNN-RAG/models/Llama-2-7b-chat-hf \
  --attn_impl flash_attention_2 \
  --batch_size 4 \
  --device cuda \
  --dtype float16 \
  --save_evidence \
  --save_prompt \
  --entity_emb entity_emb_sbert_100d.npy \
  --relation_emb relation_emb_sbert_100d.npy \
  --progress
