python src/run.py phase2 \
  --data_dir /data/GNN-RAG/datasets/webqsp \
  --split dev \
  --reader hf \
  --model_path /data/GNN-RAG/models/Llama-2-7b-chat-hf \
  --attn_impl flash_attention_2 \
  --chat_template on \
  --batch_size 8 \
  --device cuda \
  --dtype float16 \
  --save_evidence \
  --save_prompt \
  --entity_name_map src/entities_names.json \
  --entity_emb entity_emb_sbert_768d.npy \
  --relation_emb relation_emb_sbert_768d.npy \
  --question_emb question_emb_sbert_768d_dev.npy \
  --progress
